version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bookclub_postgres
    environment:
      POSTGRES_USER: bookclub_user
      POSTGRES_PASSWORD: bookclub_password
      POSTGRES_DB: bookclub_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
